# Generated by Django 5.1.6 on 2025-02-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Доменное имя')),
                ('is_accessible', models.BooleanField(default=True, verbose_name='Доступность домена (HTTP 200)')),
                ('is_blocked_api', models.BooleanField(default=False, verbose_name='Блокировка домена API')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный домен для проверки')),
                ('last_checked', models.DateTimeField(auto_now=True, verbose_name='Последняя проверка')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True, verbose_name='Telegram Chat ID')),
            ],
        ),
    ]
