# Generated by Django 5.1.6 on 2025-04-18 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='pay_domains',
            field=models.BooleanField(default=False, verbose_name='Куплен домен на замену'),
        ),
    ]
